name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Project
        run: |
          mkdir -p docs
          cp -r static/* docs/
          cp index.html docs/
          # Add any other build steps here

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/
          git commit -m "Automated build for GitHub Pages" || echo "No changes to commit"
          git push origin main
